Models/Contexto.cs
using Microsoft.EntityFrameworkCore;
namespace estudo.Models
{
    public class Context : DbContext
    {
        public Context(DbContextOptions<Context> options) : base(options)
        {
        }
        public DbSet<Mecanico> Mecanicos { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace estudo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Mecanico.cs
using System;

namespace estudo.Models
{
    public class Mecanico
    {
        public Guid Id { get; set; }
        public string RazaoSocial { get; set; }
        public string CNPJ { get; set; }
        public string Responsavel { get; set; }
        public string CPF { get; set; }
        public string Telefone { get; set; }
        public string DDDTelefone { get; set; }
        public string Celular { get; set; }
        public string DDDCelular { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string CEP { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public int NotaMedia { get; set; }
        public DateTime DataCadastro { get; set; }

    }
}

Controllers/MecanicoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using estudo.Models;
using Microsoft.EntityFrameworkCore;

namespace estudo.Controllers
{
    public class MecanicoController : Controller
    {
        private readonly Context _context;

        public MecanicoController(Context context)
        {
            _context = context;
        }

        // GET: Livros
        public async Task<IActionResult> Index()
        {
            return View(await _context.Mecanicos.ToListAsync());
        }

        // GET: Livros/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Mecanicos
                .SingleOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // GET: Livros/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Livros/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RazaoSocial,CNPJ,Responsavel,CPF,DDDTelefone,Telefone,DDDCelular,Celular,Endereco,Numero,CEP,Cidade,Estado,Latitude,Longitude")] Mecanico mecanico)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mecanico);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mecanico);
        }

        // GET: Livros/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Mecanicos.SingleOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }
            return View(livro);
        }

        // POST: Livros/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,RazaoSocial,CNPJ,Responsavel,CPF,DDDTelefone,Telefone,DDDCelular,Celular,Endereco,Numero,CEP,Cidade,Estado,Latitude,Longitude")] Mecanico mecanico)
        {
            if (id != mecanico.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mecanico);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivroExists(mecanico.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mecanico);
        }

        // GET: Livros/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Mecanicos
                .SingleOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // POST: Livros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var livro = await _context.Mecanicos.SingleOrDefaultAsync(m => m.Id == id);
            _context.Mecanicos.Remove(livro);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LivroExists(Guid id)
        {
            return _context.Mecanicos.Any(e => e.Id == id);
        }
    }
}

Views/Mecanico/Create.cshtml
@model estudo.Models.Mecanico

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cadastrar Mecânico</title>
</head>
<body>
<br />
<h4>Cadastro de Mecânico</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Razão Social</label>
                <input asp-for="RazaoSocial" class="form-control" required />
                <span asp-validation-for="RazaoSocial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">CNPJ</label>
                <input asp-for="CNPJ" class="form-control" data-mask="00.000.000/0000-00" />
                <span asp-validation-for="CNPJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Responsável</label>
                <input asp-for="Responsavel" class="form-control" />
                <span asp-validation-for="Responsavel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" data-mask="000.000.000-00"/>
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label class="control-label">Telefone</label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <input asp-for="DDDTelefone" class="form-control" placeholder="ex (11)" data-mask="(00)"/>
                        <input asp-for="Telefone" class="form-control" placeholder="ex 2253-0324" data-mask="0000-0000"/>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label">Celular</label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                         <input asp-for="DDDCelular" class="form-control" placeholder="ex (11)" data-mask="(00)" />
                        <input asp-for="Celular" class="form-control" placeholder="96905-5218" data-mask="00000-0000" />
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label">Endereço</label>
                <input asp-for="Endereco" class="form-control" required />
                <span asp-validation-for="Endereco" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label class="control-label">Número</label>
                <input asp-for="Numero" class="form-control" required />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">CEP</label>
                <input asp-for="CEP" class="form-control" data-mask="00000-000" required/>
                <span asp-validation-for="CEP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" value="São Paulo" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" value="SP"/>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" placeholder="-23.563699" required />
                <span asp-validation-for="Latitude" class="text-danger" ></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" placeholder="-46.510837" required/>
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Salvar"  class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para listagem</a>
</div>

</body>
</html>

Views/Mecanico/Delete.cshtml
@model estudo.Models.Mecanico


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Deletar Registro</title>
</head>
<body>
<br />
<h3>Você tem certeza que deseja deletar @Html.DisplayFor(model => model.RazaoSocial)?</h3>
<div>
  <br />  
    
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
        <a asp-action="Index">Voltar para listagem</a>
    </form>
</div>
</body>
</html>

Views/Mecanico/Details.cshtml
@model estudo.Models.Mecanico


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detalhes</title>
</head>
<body>

<div>
    <h4>Detalhes do Mecânico</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Razão Social
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RazaoSocial)
        </dd>
        <dt>
           CNPJ
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CNPJ)
        </dd>
        <dt>
           Responsável
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Responsavel)
        </dd>
        <dt>
           CPF
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt>
           Telefone
        </dt>
        <dd>
             @Html.DisplayFor(model => model.DDDTelefone)  @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt>
            Celular
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DDDCelular)  @Html.DisplayFor(model => model.Celular)
        </dd>
        <dt>
            Endereço
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Endereco) , CEP:  @Html.DisplayFor(model => model.CEP),  @Html.DisplayFor(model => model.Cidade),  @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt>
           Latitude
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt>
            Longitude
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>
         <dt>
            Nota Média
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NotaMedia)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-outline-primary" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Voltar a listagem</a>
</div>
</body>
</html>

Views/Mecanico/Edit.cshtml
@model estudo.Models.Mecanico

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Editar</title>
</head>
<body>

<h4>Editação Mecânico</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
           <div class="form-group">
                <label class="control-label">Razão Social</label>
                <input asp-for="RazaoSocial" class="form-control" required />
                <span asp-validation-for="RazaoSocial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">CNPJ</label>
                <input asp-for="CNPJ" class="form-control" data-mask="00.000.000/0000-00" />
                <span asp-validation-for="CNPJ" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Responsável</label>
                <input asp-for="Responsavel" class="form-control" />
                <span asp-validation-for="Responsavel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" data-mask="000.000.000-00"/>
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label class="control-label">Telefone</label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <input asp-for="DDDTelefone" class="form-control" placeholder="ex (11)" data-mask="(00)"/>
                        <input asp-for="Telefone" class="form-control" placeholder="ex 2253-0324" data-mask="0000-0000"/>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label">Celular</label>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                         <input asp-for="DDDCelular" class="form-control" placeholder="ex (11)" data-mask="(00)" />
                        <input asp-for="Celular" class="form-control" placeholder="96905-5218" data-mask="00000-0000" />
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label">Endereço</label>
                <input asp-for="Endereco" class="form-control" required />
                <span asp-validation-for="Endereco" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label class="control-label">Número</label>
                <input asp-for="Numero" class="form-control" required />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">CEP</label>
                <input asp-for="CEP" class="form-control" data-mask="00000-000" required/>
                <span asp-validation-for="CEP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" value="São Paulo" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" value="SP"/>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" placeholder="-23.563699" required />
                <span asp-validation-for="Latitude" class="text-danger" ></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" placeholder="-46.510837" required/>
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Salvar"  class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar a listagem</a>
</div>

</body>
</html>

Views/Mecanico/Index.cshtml
@model IEnumerable<estudo.Models.Mecanico>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cadastro de Mecânicos</title>
    <style>
        .table-bordered th, .table-bordered td
        {
            border: none;
        }
    </style>
</head>
<body>
   </br>

<p>
    <a asp-action="Create" class="btn btn-outline-primary">Cadastrar Mecânico</a>
</p>
<table class="table-striped table-bordered" style="width:100%;">
    <thead>
        <tr>
                <th style="padding: 5px;">
                   Razão Social
                </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td style="padding: 5px; width:100%;">
                @Html.DisplayFor(modelItem => item.RazaoSocial)
            </td>
            <td >
 <a asp-action="Edit" class="btn btn-outline-dark" asp-route-id="@item.Id"><span class="fas fa-edit"></span ></a> 
            </td>
            <td>

                <a asp-action="Details" class="btn btn-outline-dark" asp-route-id="@item.Id"><span class="fas fa-eye"></span ></a> 
            </td>
               <td>
                <a asp-action="Delete" class="btn btn-outline-danger" asp-route-id="@item.Id"><span class="fas fa-fire"></span ></a>
           
            </td>
        </tr>
}
    </tbody>
</table>

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - estudo</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
 
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Milese Plataforma - <a asp-area="" asp-controller="Mecanico" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>        
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/lib/jquery-mask-plugin/dist/jquery.mask.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>